### ISSUE TITLE
Why FlexColorScheme.themedSystemNavigationBar can't modify systemNavigationBarIconBrightness?

### ISSUE THREAD

**Issue by liyuhaolol** [rydmike/sysnavbar#1]
My English is not very good, please forgive me. 

When I use 3-button navigation, I find that I can't customize systemNavigationBarIconBrightness in the light background, which causes the button can't see clearly. 

I read the source code and find that, systemNavigationBarIconBrightness is set automatically according to DarkMode, and the interface is not exposed for developer to customize.
```dart
systemNavigationBarIconBrightness:
          isDark ? Brightness.light : Brightness.dark,
```

This creates a problem, that is, not all people use Gesture navigation, many people use 3-button navigation. This will not achieve that effect.

So I think we should add a method that can modify systemNavigationBarIconBrightness, and only take effect above Android R. under Android Q just follows the FlexColorScheme rule.

I wonder if you think this requirement is reasonable?

**Comment by rydmike** [comment]
Hi @liyuhaolol thanks for your feedback! 👍🏻 
Your English looks great to me, I'm not English either 😄 

I am certainly open to improving how the system navigation bar is tackled in **FlexColorScheme**. It is quite a tricky topic with many open issues also in Flutter SDK, especially regarding using a transparent system navigation bar. There is still some work going on regarding that, so maybe there will be some solution that can support it on a bit lower SDK 30 as well.

One key limitation for **FlexColorScheme** with regards to the system navigation bar, is that FlexColorScheme really only deals with ThemeData and what can be done via it. As a rather new thing, the AppBar sub-theme includes a `SystemUiOverlayStyle` that the latest version of FlexColorScheme now also uses and adjusts. However, there is not really any sub theme in ThemeData (that I know of) that could otherwise be used to automatically theme the system navigation bar. 

This means means that the system navigation bar still has to be handled as desired in the app, usually by wrapping at least the same three that handles the theme switching with an `AnnotatedRegion<SystemUiOverlayStyle>` that sets the system navigation bar style as desired, usually of course to match the current light and dark mode correctly, just like you describe.

**FlexColorScheme** makes no direct calls to adjust the system navigation bar, just like Flutter ThemeData does not really do it either, other than for the AppBar, that does it for the status bar and its icons, which FlexColorScheme also uses.

There is however a static helper function in `FlexColorScheme` called `themedSystemNavigationBar` that can be used together with the `AnnotatedRegion` to make the system navigation bar style match the current theme. This is how you would use it:

```dart
 // ...in any build function return
  return AnnotatedRegion<SystemUiOverlayStyle>(
      value: FlexColorScheme.themedSystemNavigationBar(context),
      child: ...
```

The **FlexColorScheme** docs talk about this a bit here:
https://pub.dev/packages/flex_color_scheme#example-5---themed-system-navigation-bar-in-android
And it is demonstrated in example 5.

This `sysnavbar` repo is a more advanced use case of it, discussed in the docs here:
https://pub.dev/packages/flex_color_scheme#android-transparent-system-navigation-bar

## Why not just call `SystemChrome.setSystemUIOverlayStyle`  in FlexColorScheme?

I have found that just calling calling `SystemChrome.setSystemUIOverlayStyle` with a SystemUiOverlayStyle style does not work so well, you sometimes get the style sometimes not, and when you restore from other apps that had some other style, the style might be missing again. Of course, if you call it from enough screens build (probably not very good for performance) in your app, it usually takes effect at some point, but from just doing it in a call where the theme is made, like you could do in FlexColorScheme, does not work. I certainly tried doing it like that too, but it just did not always take effect or work properly.

The Flutter way of addressing this is by adding an `AnnotatedRegion` with the desired `SystemUiOverlayStyle` style to your Widget tree. I have found that it it works well when placed at the top where your theme is changed, and depending on theme you adjust it as needed. If some sub-screens need a system navigation bar that is different from the rest of your app, you have to insert another `AnnotatedRegion` at that point in the tree as well. That is what I am doing with the sub page in this **sysnavbar** demo as well, just for demo purposes. in the example 5, the annotated region is only higher up in the three and the sub pages still gets the same themed system navigation bar.

The static helper `themedSystemNavigationBar` has a few other parameters that can be convenient to use as well. You can read more about them here:
https://pub.dev/documentation/flex_color_scheme/latest/flex_color_scheme/FlexColorScheme/themedSystemNavigationBar.html

I just noticed there were a bunch of typos and other short comings in those doc comments. I just corrected it a bit, but it it won't be on pub.dev until I release a new version. The GH link to the updated version is: https://github.com/rydmike/flex_color_scheme/blob/master/lib/src/flex_color_scheme.dart#L1255 )

You don't have to use `FlexColorScheme.themedSystemNavigationBar(context)`, you can just as easily make and add your own `SystemUiOverlayStyle` that is designed any way you need it to be.

```dart
 // ...in any build function return
  return AnnotatedRegion<SystemUiOverlayStyle>(
      value: SystemUiOverlayStyle(...),
      child: ...
```

---

I don't know if any of this answers your question. Also if you have some solution that you think would work, please feel free to provide an example, I would be happy to try it as well. 😃 

BTW, I must admit, I have not tried adjusting the system nav bar by adjusting it via the rather new SystemUiOverlayStyle included  the AppBarTheme. I'm only adjusting the top status bar via it, since as far as I know, the AppBar is not supposed to adjust the system nav bar, but maybe it can or could, I will dig into the latest SDK to take a look at it again.

If it can be done via the SDK AppBarTheme, and it works OK, then doing so could be a really convenient way to get it done in FlexColorScheme in a way that works for all screens that has an AppBar (which most screens usually have), then you would only need an AnnotatedRegion for any screens that do not use a Material AppBar. Is this perhaps what you are suggesting? In any case I'm going to test how and if this might work, sounds interesting...

**Comment by rydmike** [comment]
Hi again @liyuhaolol, having looked a bit closer at what the new AppBar theme in Flutter SDK 2 does with the overlay style a bit closer, this:

```dart
    final Brightness overlayStyleBrightness = widget.brightness ?? appBarTheme.brightness ?? colorScheme.brightness;
    final SystemUiOverlayStyle overlayStyle = backwardsCompatibility
      ? (overlayStyleBrightness == Brightness.dark ? SystemUiOverlayStyle.light : SystemUiOverlayStyle.dark)
      : widget.systemOverlayStyle
        ?? appBarTheme.systemOverlayStyle
        ?? (colorScheme.brightness == Brightness.dark ? SystemUiOverlayStyle.light : SystemUiOverlayStyle.dark);
```

I see the issue that I think you are referring to as well. This was not the case with how it was done in the past. This is cool though, it offers new possibilities.

I will fix this, thanks for the heads up on it. 👍🏻 

I will do it so AppBar can still, as now support the transparency, one toned AppBar on Android, that I like, like iOS does it, if so desired, but also sets system navbar using comparable style as those light and dark constructors on the system navbar.

I will use a property that by default sets system navbar to use default (black/white) for dark/light theme on navigation bar, but also has option for using background color or surface color, or scaffold background color, which may or may not be primary color blended, depending on how you defined the FlexColorScheme surface property. With this you will not need any AnnotatedRegion on screens that has an AppBar, even if you want to the background color of your system navigation bar to match one of the branded surface color ptions. This will actually be a nice new feature. Annotated region will still be needed if you don't have an AppBar, but it will not be needed in most cases anymore, cool.

Well let's see how it works out... It should work if that `systemOverlayStyle` in the new AppBarTheme in Flutter SDK 2 actually also has an effect on the system navigation bar. I will know soon after some tests...

**Comment by rydmike** [comment]
@liyuhaolol It seems it is still like I recalled that it was with previous version, the system navbar does not get changed at all from the AppBarTheme even if some systemOverlayStyle that contains such data is used, it really only seems to affect the AppBar's statusbar.

The overlay style it uses, SystemUiOverlayStyle.dark and SystemUiOverlayStyle.light actually only contain differences when it comes to the app bar and its status bar region. The system navbar is always black background with light (white) nav buttons, as can be seen here (from system_chrome.dart) they are the same:

```dart
  /// System overlays should be drawn with a light color. Intended for
  /// applications with a dark background.
  static const SystemUiOverlayStyle light = SystemUiOverlayStyle(
    systemNavigationBarColor: Color(0xFF000000),
    systemNavigationBarDividerColor: null,
    statusBarColor: null,
    systemNavigationBarIconBrightness: Brightness.light,
    statusBarIconBrightness: Brightness.light,
    statusBarBrightness: Brightness.dark,
  );
  /// System overlays should be drawn with a dark color. Intended for
  /// applications with a light background.
  static const SystemUiOverlayStyle dark = SystemUiOverlayStyle(
    systemNavigationBarColor: Color(0xFF000000),
    systemNavigationBarDividerColor: null,
    statusBarColor: null,
    systemNavigationBarIconBrightness: Brightness.light,
    statusBarIconBrightness: Brightness.dark,
    statusBarBrightness: Brightness.light,
  );
```

So even if I change the `systemNavigationBarColor` and `systemNavigationBarIconBrightness` in the `appBarTheme.systemOverlayStyle` they don't actually change the style of the system navigation bar in any manner when you define the values via the AppBarTheme. The AppBarTheme is the only place that  know that sets its own AnnotatedRegion of available sub-themes, and it seems it has no impact on the system navigation bar, probably on purpose. So we are probably stuck with defining it via an annotated region.

Even if I drop in the settings:

```dart
    systemNavigationBarColor: Color(0xFF000000),
    systemNavigationBarDividerColor: null,
    systemNavigationBarIconBrightness: Brightness.light,
```

Into the config in FlexColorScheme for its AppBarTheme's systemOverlayStyle, it as you see that just sets the icons to light, which would be invisible in light theme mode **when and if** the navigation bar background for whatever reason has been made white (or light). So I don't think it matters what it says.

I tried it but the darn parameters do not change via the AppBar theming at all, so it looks like the `AnnotatedRegion` is really required when you want to change the system navigation bar and its icons. This also applies to making it light (white) in light theme and with the dark grey buttons, even if done without FlexColorScheme.

----

I will do some more experimentation, I'm a bit out of ideas at the moment, but I'm happy to hear suggestions.

It would be really nice if Flutter offered a way to theme the system navigation bar, also transparency. Maybe we should make such a proposal. Dealing with the system navigation bar via an annotated regions feel really backwards instead of being able to do it via active theme, likewise for its transparent version.

**Comment by rydmike** [comment]
@liyuhaolol Just for info, I did some experiments on the topic and published it in an experimental branch. Here you can see what I tried:

https://github.com/rydmike/flex_color_scheme/blob/system-overlay-style-experiments/lib/src/flex_color_scheme.dart#L2132

I really wanted to be able to support styling the system navigation bar via an enum in FlexColorScheme:
https://github.com/rydmike/flex_color_scheme/blob/system-overlay-style-experiments/lib/src/flex_color_scheme.dart#L84

By sneaking in the settings via the AppBarTheme, but it does not work, does not really do anything. Just callign SystemChrome also does not work correctly, you really need to use an annotated region, like the SDK docs say too:

https://api.flutter.dev/flutter/services/SystemChrome/setSystemUIOverlayStyle.html
> "For more complex control of the system overlay styles, consider using an AnnotatedRegion widget instead of calling setSystemUIOverlayStyle directly. This widget places a value directly into the layer tree where it can be hit-tested by the framework. On every frame, the framework will hit-test and select the annotated region it finds under the status and navigation bar and synthesize them into a single style. This can be used to configure the system styles when an app bar is not used."

If you build example 5 in the experimental branch you can try it out:
https://github.com/rydmike/flex_color_scheme/tree/system-overlay-style-experiments/example/lib/example5

I will still leave that `FlexSystemNavBarStyle` in there and add it to a new release **FlexColorScheme** as well. I added support for it to the `themedSystemNavigationBar` that should work OK when used in an `AnnotatedRegion` as described above in previosu posts. You could of course do that before to by just passing it the desired color. This is more of a convenience addition. I also want keep the enum around in case there later is a way, or we figure out a way to style it via the theme setup, then it can be used there then as well.

https://github.com/rydmike/flex_color_scheme/blob/system-overlay-style-experiments/lib/src/flex_color_scheme.dart#L1376

I also fixed in the top statusbar, before if you had set it to transparent it did not really work if you toggled it back to not being transparent anymore, unless you rebuilt the app totally. Setting the value to 'null' as it is by default will not restore it, you have to give it the actual scrim Color used by default in Android to get the default style back.
That fix is here: https://github.com/rydmike/flex_color_scheme/blob/system-overlay-style-experiments/lib/src/flex_color_scheme.dart#L2135

Had to figure out what the default scrim is for that, was not in docs anywhere that I could find, but got it now:
https://twitter.com/RydMike/status/1373020259934953475?s=20

I think there is a similar issue for the divider color on the sysnavbar, getting it removed when saying you don't want it, need to set color to whatever it needs to be to go away after it has been used. I will figure that what that color is too and add it to the config `themedSystemNavigationBar` so it can be properly toggled. It is currently like the status navbar was, if you enabled it, you must completely rebuild the app to get rid of it again, restart does not even remove it. So I think the solution for that is very similar to the status bar scrim.

---

I need to clean up these fixes and changes via another branch, add tests and docs for them and publish a 2.1.0 update to **FlexColorScheme**.

It still does not do what you want via theming, as it does not seem to be doable. But in any case, I think two fixes will come out of experiments that you question started plus one convenience improvement. So that is certainly be something. And I will add more info on the system nav bar theming to the docs, although there is already quite a bit on it, see links above in previous replies.

**Comment by liyuhaolol** [comment]
Hello, I really can't think about the overall situation like you. Because I didn't fully read the framework code. But here are a simple examples to show what i think.

```dart 
//
@override
Widget build(BuildContext context) {
  return MaterialApp(
    title: 'Flutter Demo',
    home: AnnotatedRegion<SystemUiOverlayStyle>(
      value: FlexColorScheme.themedSystemNavigationBar(context,
              opacity: widget.androidLevel > 29 ? 0.002 : 1,
              systemNavigationBarColor: Colors.deepPurple,
              systemNavigationBarDividerColor: Colors.deepPurple, ),
      child: Scaffold(
      body: Container(color: Colors.black,),
      ),
    ),
  );
}
//
```

#### Android10 has a deepPurple navigationbar,but navigationbaricon can't change to lightmod.

<div><img src='https://raw.githubusercontent.com/liyuhaolol/image_app/master/pack/Q.png' width="300px"/></div>

#### Android11 navigationbar above black Container,but navigationbaricon can't change to lightmod.

<div><img src='https://raw.githubusercontent.com/liyuhaolol/image_app/master/pack/R.png' width="300px"/></div>

#### statusbaricon has same situation,if change black color to white, we won't be able to see statusbaricon clearly.

This problem is because `FlexColorScheme.themedSystemNavigationBar` can't modify `statusBarBrightness`,`statusBarIconBrightness`,`systemNavigationBarIconBrightness`.

`isDark == false` doesn't mean that it must be `Brightness.dark`

So I think these three attributes should be added to let developers decide whether to modify them according to their needs

- statusBarBrightness

- statusBarIconBrightness

- systemNavigationBarIconBrightness

```dart

statusBarBrightness: statusBarBrightness == null
        ? noAppBar
        ? (isDark ? Brightness.dark : Brightness.light)
        : null
        :statusBarBrightness,

statusBarIconBrightness: statusBarIconBrightness == null
        ? noAppBar
        ? invertStatusIcons
        ? (isDark ? Brightness.dark : Brightness.light)
        : (isDark ? Brightness.light : Brightness.dark)
        : null
        :statusBarIconBrightness,
        
systemNavigationBarIconBrightness: systemNavigationBarIconBrightness == null
        ? (isDark ? Brightness.light : Brightness.dark)
        :systemNavigationBarIconBrightness,
```

After making these code modifications, if the developer modifies the attribute, it will be executed according to the developer's wishes. 
If the developer does not modify the attribute, it will be executed according to the default logic of `FlexColorScheme`.

I think this will not interfere with the original logic of `FlexColorScheme`, but also achieve the developer's custom requirements.

I don't know if my idea is reasonable.

**Comment by rydmike** [comment]
Hi, thanks for the example! This totally explains your usage scenario and explains your question.

Yes for `FlexColorScheme.themedSystemNavigationBar` it is indeed possible to do this, but if it is needed and sensible is another question, I will explain more about that further below. 

First though, the reason I did not understand your question was that I thought you were looking for a way that this could be done as a built in feature in the Themes produced by `FlexColorScheme.toTheme`, which is not doable in current SDK. I really wish it was, it would be so much nicer to get it all done that way.

The `FlexColorScheme.themedSystemNavigationBar` could of course do what you suggest. The reason why it does not currently do so is because it was really only intended to be used as a short convenience static function to return a `SystemUiOverlayStyle` that has a theme `colorScheme.background` colored system navbar and not much else. I later added the color and divider to give it a bit more flexibility, but still intended it to be used only for a color that is of same Brightness as the theme mode background color would be. The current value for the `systemNavigationBarIconBrightness` always depends on theme brightness and always strive to be visible on the brightness of theme brightness, so basically always reverse brightness of the theme's brightness.

In the above example you create a Material app with a default theme, so the app is using a light theme, thus the app is expecting background to be white and `themedSystemNavigationBar` to be of a color that would evaluate to Brightness.dark and thus the system navbar icons when using this helper in this theme, want to be dark. The intended usage with it is the `themed` part in the static helper name, it is supposed to produce a system navbar suitable for the active theme mode (light or dark). It was only designed to help with that usage and provide a short and convenient helper for just that use case.

In your example, you cover the Scaffold with a black container, but theme is still light, thus it is expecting a light background and also a color of Brightness.light on the sysnavbar and thus logically keeps Brightness.dark for the icons. If your example would use dark theme mode, then the systemNavigationBarIconBrightness would become light.

I could certainly add the freedom to do whatever desired in this `themedSystemNavigationBar` helper too, but at some point it just becomes the same thing as just using the `SystemUiOverlayStyle` in the annotated region directly. Which when you are doing some really custom system navbar setup is probably what you want to use anyway, especially if theme mode brightness does not match the brightness of the color you are using in the apps sys navbar. Which I guess could be a case if some single page needs to do so for some specific use case in the app and go against the Brightness of the current active theme mode, which normally would not be a thing that is done.

Still for those scenarios and such pages, I would just use a `SystemUiOverlayStyle` directly in the `AnnotatedRegion` then configure it however needed. There is no need to use `FlexColorScheme.themedSystemNavigationBar` to style the `AnnotatedRegion`, even if you are otherwise using FlexColorScheme to theme your app, you can just do a:

```dart
@override
Widget build(BuildContext context) {
  return MaterialApp(
    title: 'Flutter Demo',
    home: AnnotatedRegion<SystemUiOverlayStyle>(
      value: SystemUiOverlayStyle(
        statusBarColor: ...,
        statusBarBrightness: ...,
        statusBarIconBrightness: ...,
        // The bottom navigation bar settings.
        systemNavigationBarColor: ...,
        systemNavigationBarDividerColor: ...,
        systemNavigationBarIconBrightness: ...,
      );,
      child: Scaffold(
      body: Container(color: Colors.black,),
      ),
    ),
  );
}
```

And above set the `SystemUiOverlayStyle` as needed for the app/page in question. The `themedSystemNavigationBar` static helper was really just intended to be able to do this:

```dart
    return AnnotatedRegion<SystemUiOverlayStyle>(
      value: FlexColorScheme.themedSystemNavigationBar(context),
      child: ...
```

Without the need for always using the much more verbose `SystemUiOverlayStyle` object, just to easily give you a system overlay style that gives you a theme based background colored sys navbar, without the need to define all the details yourself.

But since with latest, and even more upcoming features, you can use divider (even give it your own color), and select to use not just `colorScheme.background` but also other theme backgrounds as well (system, surface, scaffold), like:

```dart
    return AnnotatedRegion<SystemUiOverlayStyle>(
      value: FlexColorScheme.themedSystemNavigationBar(context,
        systemNavBarStyle: FlexSystemNavBarStyle.surface,  // This coming in next release
        useDivider: true,
      ),
      child: ...
```

I guess exposing the `systemNavigationBarIconBrightness` and other props, like you propose, could be added as well. I will think about it. 

Here are my thought about why it is not a good idea.

If done, then `themedSystemNavigationBar` just becomes a full wrapper for `SystemUiOverlayStyle` with a few extra convenience parameters added to it, and as mentioned before, for that you can just as well use `SystemUiOverlayStyle`. So the question then becomes why do that all? There is really no need for that, because for such cases one can just as well use `SystemUiOverlayStyle` directly instead.

Still I will think about it a bit. 

Also keep in mind, the `themedSystemNavigationBar` is just a static helper function on `FlexColorScheme`, you can easily make your own function anywhere in your app to define a convenience helper and wrapper for `SystemUiOverlayStyle` that contains convenience features/shortcuts for what you need. 

The bundled `themedSystemNavigationBar` helper is only intended to cover the most typical use case. The issue with helper functions is really that they should never really cover all use cases of what they are wrapping for convenience, because at that point they become the very thing they wrap, and are not really more convenient anymore and you can just use what they wrap instead. 

Still happy to hear you arguments for exposing all props of `SystemUiOverlayStyle` in `themedSystemNavigationBar`. However, I also hope this explains a bit why it only does what it currently does and not everything `SystemUiOverlayStyle` does.

**Comment by rydmike** [comment]
@liyuhaolol All the above being said, I guess I could still add the properties to the wrapper helper. Mostly because it still offers some syntactic sugar that are more convenient to use than raw `SystemUiOverlayStyle`, I kind of prefer using it myself too over the raw version. So I will try it out to see how it feels. The biggest part of adding it is actually adding all the tests needed for the new exposed properties in order to not reduce current test coverage.

**Comment by rydmike** [comment]
@liyuhaolol 
As you can see I thought about this quite a bit and even tried the option of adding all `SystemUiOverlayStyle` properties to the `FlexColorScheme.themedSystemNavigationBar`. However, eventually I decided against it. It goes against this helper functions naming and purpose of just being a helper that adheres to the theme and provides a nice default and optional convenience properties for system navigation bar styling that should follow the active theme, and that can also address top status bar when an AppBar is not used.

Like I mentioned earlier, for none theme related styles, it is better to just use `SystemUiOverlayStyle` directly where you already have full control of all properties, there is really no point in offering a duplicate for that purpose.

The **FlexColorScheme** package just got a new release with some related fixes, that I actually stumbled over while addressing your questions from different angles, so it brought forward some use cases I had not tackled before and issues related to them that got fixed, so thanks for that! 😃 

In the new release I also updated the docs about this topic:
https://pub.dev/packages/flex_color_scheme#example-5---themed-system-navigation-bar-in-android

And added this comment to this example repo's readme as well:

> **NOTE:**  
> The static helper `FlexColorScheme.themedSystemNavigationBar(context, ...)` is designed to provide a 
> convenience wrapper for a `SystemUiOverlayStyle` that works for screens that use 
> and adhere to current theme mode colors.
> 
> If your application use screens that do not follow the current theme, then just use `SystemUiOverlayStyle`
> directly in the annotated region for such screens to define their desired style. You can also make your own
> convenience wrapper function or even just a const value for it if you need to use a fixed style and 
> design frequently.

While it is probably not the answer you wished for, I feel that since just using a `SystemUiOverlayStyle` directly for more custom designs is a totally valid and Flutter SDK way of covering such designs, it should enable you to achieve your custom design as well.

**Comment by rydmike** [comment]
I hope the questions have been properly answered. Closing this issue. You are welcome to ask additional question on this topic if you like.
