### ISSUE TITLE
Is there a Java equivalent to the Kotlin used in the readme?

### ISSUE THREAD

**Issue by GroovinChip** [rydmike/sysnavbar#2]
I'd like to do this setup in a Flutter app that was created without Kotlin support. Is there a Java equivalent?

**Comment by rydmike** [comment]
@GroovinChip I'm sure there is, sadly it is not my area of expertise either.  There might be some clues in the all the different issues in the Flutter repos that deal with this topic. This are the ones that I know of that discuss this topic:

https://github.com/flutter/flutter/issues/34678
https://github.com/flutter/flutter/issues/35748
https://github.com/flutter/flutter/issues/40974
https://github.com/flutter/flutter/issues/69999

I got this setup from the last one above. I don't really have any more insights into it either.

As you can see in the issues, Flutter team members have been and are involved in the issues, but to date there is no solution that can work from Flutter side only. Piinks seem to be the person with a current interest in it, e.g. https://github.com/flutter/flutter/issues/40974#issuecomment-812149339

I've been meaning to add some comments about it working with the old style buttons navs too, and that you can get them on a fully transparent background too, but not if you make the background fully transparent, then the system always applies a semi transparent scrim to the navbar area, but it you make the sys navbar background with a 0.5% opacity or alpha 0x01, then it will look fully transparent, just a thing I discovered in this demo with the opacity slider in it.

I would also like to have a solution for this that works Flutter side only, and from API 29 and up and not just API 30 + Android configs. At least natively Android apps have been doing this since API 29 already.

**Comment by GroovinChip** [comment]
Gotcha, thanks for the info Mike!
